module aftermath.expressions.operators {
    var equal: BinaryPredicateOperator;
    var notEqual: BinaryPredicateOperator;
    var greaterThan: BinaryPredicateOperator;
    var greaterThanEqual: BinaryPredicateOperator;
    var lessThan: BinaryPredicateOperator;
    var lessThanEqual: BinaryPredicateOperator;
    var and: BinaryPredicateOperator;
    var add: BinaryOperator;
    var subtract: BinaryOperator;
    var multiply: BinaryOperator;
    var divide: BinaryOperator;
    var modulo: BinaryOperator;
    var distanceTo: BinaryOperator;
    var contains: BinaryOperator;
    var startsWith: BinaryOperator;
    var endsWith: BinaryOperator;
    var indexOf: BinaryOperator;
}
